"use client"

import Link from "next/link";
import { useState } from "react";
import { IoChevronBack } from "react-icons/io5";
import kkk from "../../lib/image/KKK.png"
import Image from "next/image";



const Remarks = () => {
    const [selectedRegion, setSelectedRegion] = useState<string>("");
    const partialButtons = [
        { id: "inc1", text: "Incomplete hard copy of documents" },
        {
            id: "inc2",
            text: "Hardcopy documents were transmitted more than 5 days from submission of online registration",
        },
        {
            id: "inc3",
            text: "Invalid GDrive link redirected to My Drive (No candidate file).",
        },
        {
            id: "inc4",
            text: "Incomplete GDrive link IDs / Affidavit of Undertaking / Authority to Register OCP.",
        },
    ];
    const nonComplianceButtons = [
        { id: "nc1", text: "No URL of Online Campaign Platform" },
        {
            id: "nc2",
            text: "GDrive link of uploaded required documents cannot be accessed / restricted",
        },
        { id: "nc3", text: "No Transmittal of hard copy documents" },
        {
            id: "nc4",
            text: "No URL of Online Campaign Platform. GDrive link of uploaded required documents cannot be accessed / restricted.",
        },
        {
            id: "inc3",
            text: "No Gdrive link for Valid IDs / Affidavit of Undertaking / Authority to Register OCP",
        },
        {
            id: "inc4",
            text: "Failure to Online Register Campaign Platform (Section 7, Article III of COMELEC Resolution No. 11064, as amended)",
        },
    ];

    const fullComplianceButtons = [
        { id: "nc5", text: "Facebook link is not accessible to public." },
    ];

    const copyText = (text: string, id: string) => {
        // const upperCase: string = text.toUpperCase();
        navigator.clipboard
            .writeText(text)
            .then(() => {
                console.log(`Copied: ${text} (ID: ${id})`);
            })
            .catch((err) => {
                console.error("Failed to copy text: ", err);
            });
    };

    const handleRegionChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        setSelectedRegion(event.target.value);
    };

    return (
        <div className="h-full w-full overflow-y-auto  bg-slate-300  text-slate-950 flex flex-col justify-center items-center">
            <div className="w-full mt-4 px-2">
                <Link href="/" className="flex gap-1 items-center font-semibold hover:text-blue-700"><IoChevronBack className="text-[2rem]" />BACK</Link>
            </div>

            <div className="px-20 w-full flex-col flex items-center justify-center">
                <div className="font-semibold tracking-widest text-[2.5rem] flex items-center">
                    <Image src={kkk} alt="Description of image" width={100} height={50} />
                    <label className="">REMARKS</label>
                </div>
                <button
                    className="partial-h1"
                    onClick={() => copyText("Partially Compliant", "")}
                >
                    PARTIALLY COMPLIANT
                </button>{" "}
                {partialButtons.map((button) => (
                    <button
                        key={button.id}
                        className="partial"
                        onClick={() => copyText(button.text, button.id)}
                    >
                        {" "}
                        {button.text}{" "}
                    </button>
                ))}{" "}
                <button className="non-h1" onClick={() => copyText("Not Compliant", "")}>
                    NOT COMPLIANT
                </button>{" "}
                {nonComplianceButtons.map((button) => (
                    <button
                        key={button.id}
                        className="non"
                        onClick={() => copyText(button.text, button.id)}
                    >
                        {" "}
                        {button.text}{" "}
                    </button>
                ))}{" "}
                <button className="full-h1" onClick={() => copyText("Compliant", "")}>
                    COMPLIANT
                </button>{" "}
                {fullComplianceButtons.map((button) => (
                    <button
                        key={button.id}
                        className="full"
                        onClick={() => copyText(button.text, button.id)}
                    >
                        {" "}
                        {button.text}{" "}
                    </button>
                ))}{" "}

                <div className="mt-10 mb-10 h-[1px] w-[80%] bg-slate-700" />
                <h1 className="mb-3 tracking-widest font-semibold text-[1.4rem]">REGIONS</h1>{" "}
                <select
                    className=" w-full py-2 rounded-md mb-2 px-2 text-black outline-none"
                    onChange={handleRegionChange}
                    value={selectedRegion}
                >
                    {" "}
                    <option value="">Select Region</option>{" "}
                    {philippinesData.map((region) => (
                        <option key={region.region} value={region.region}>
                            {" "}
                            {region.region}{" "}
                        </option>
                    ))}{" "}
                </select>{" "}
                {selectedRegion && (
                    <div className="w-full text-black">
                        {philippinesData
                            .find((region) => region.region === selectedRegion)
                            ?.provinces.map((province) => (
                                <div key={province.name} className="province-item">
                                    {" "}
                                    <button
                                        className="text-white w-full  border-[1px] rounded-md py-2 font-semibold border-slate-400 bg-slate-900 hover:bg-blue-800"
                                        onClick={() => copyText(province.name, "")}
                                    >
                                        {" "}
                                        {province.name}{" "}
                                    </button>{" "}
                                    <div className="municipality-container">
                                        {" "}
                                        <div className="municipality-grid">
                                            {" "}
                                            {province.municipalities.map((municipality) => (
                                                <button
                                                    key={municipality}
                                                    className="w-full  border-[1px] rounded-md py-2 font-normal border-slate-400 hover:bg-blue-800"
                                                    onClick={() => copyText(municipality, "")}
                                                >
                                                    {" "}
                                                    {municipality}{" "}
                                                </button>
                                            ))}{" "}
                                        </div>{" "}
                                    </div>{" "}
                                </div>
                            ))}{" "}
                    </div>
                )}{" "}
            </div>
        </div>
    );
};

export default Remarks;


const philippinesData = [
    {
        region: "Region I - Ilocos Region",
        provinces: [
            {
                name: "Ilocos Norte",
                municipalities: [
                    "Adams",
                    "Bacarra",
                    "Badoc",
                    "Bangui",
                    "Banna",
                    "Batac City",
                    "Burgos",
                    "Carasi",
                    "Currimao",
                    "Dingras",
                    "Dumalneg",
                    "Laoag City",
                    "Marcos",
                    "Nueva Era",
                    "Pagudpud",
                    "Paoay",
                    "Pasuquin",
                    "Piddig",
                    "Pinili",
                    "San Nicolas",
                    "Sarrat",
                    "Solsona",
                    "Vintar",
                ],
            },
            {
                name: "Ilocos Sur",
                municipalities: [
                    "Alilem",
                    "Banayoyo",
                    "Bantay",
                    "Burgos",
                    "Cabugao",
                    "Candon City",
                    "Caoayan",
                    "Cervantes",
                    "Galimuyod",
                    "Gregorio del Pilar",
                    "Lidlidda",
                    "Magsingal",
                    "Nagbukel",
                    "Narvacan",
                    "Quirino",
                    "Salcedo",
                    "San Emilio",
                    "San Esteban",
                    "San Ildefonso",
                    "San Juan",
                    "San Vicente",
                    "Santa",
                    "Santa Catalina",
                    "Santa Cruz",
                    "Santa Lucia",
                    "Santa Maria",
                    "Santiago",
                    "Santo Domingo",
                    "Sigay",
                    "Sinait",
                    "Sugpon",
                    "Suyo",
                    "Tagudin",
                    "Vigan City",
                ],
            },
            {
                name: "La Union",
                municipalities: [
                    "Agoo",
                    "Aringay",
                    "Bacnotan",
                    "Bagulin",
                    "Balaoan",
                    "Bangar",
                    "Bauang",
                    "Burgos",
                    "Caba",
                    "Luna",
                    "Naguilian",
                    "Pugo",
                    "Rosario",
                    "San Fernando City",
                    "San Gabriel",
                    "San Juan",
                    "Santo Tomas",
                    "Santol",
                    "Sudipen",
                    "Tubao",
                ],
            },
            {
                name: "Pangasinan",
                municipalities: [
                    "Agno",
                    "Aguilar",
                    "Alaminos City",
                    "Alcala",
                    "Anda",
                    "Asingan",
                    "Balungao",
                    "Bani",
                    "Basista",
                    "Bautista",
                    "Bayambang",
                    "Binalonan",
                    "Binmaley",
                    "Bolinao",
                    "Bugallon",
                    "Burgos",
                    "Calasiao",
                    "Dagupan City",
                    "Dasol",
                    "Infanta",
                    "Labrador",
                    "Laoac",
                    "Lingayen",
                    "Mabini",
                    "Malasiqui",
                    "Manaoag",
                    "Mangaldan",
                    "Mangatarem",
                    "Mapandan",
                    "Natividad",
                    "Pozorrubio",
                    "Rosales",
                    "San Carlos City",
                    "San Fabian",
                    "San Jacinto",
                    "San Manuel",
                    "San Nicolas",
                    "San Quintin",
                    "Santa Barbara",
                    "Santa Maria",
                    "Santo Tomas",
                    "Sison",
                    "Sual",
                    "Tayug",
                    "Umingan",
                    "Urbiztondo",
                    "Urdaneta City",
                    "Villasis",
                ],
            },
        ],
    },
    {
        region: "Region II - Cagayan Valley",
        provinces: [
            {
                name: "Batanes",
                municipalities: [
                    "Basco",
                    "Itbayat",
                    "Ivana",
                    "Mahatao",
                    "Sabtang",
                    "Uyugan",
                ],
            },
            {
                name: "Cagayan",
                municipalities: [
                    "Abulug",
                    "Alcala",
                    "Allacapan",
                    "Amulung",
                    "Aparri",
                    "Baggao",
                    "Ballesteros",
                    "Buguey",
                    "Calayan",
                    "Camalaniugan",
                    "Claveria",
                    "Enrile",
                    "Gattaran",
                    "Gonzaga",
                    "Iguig",
                    "Lal-lo",
                    "Lasam",
                    "Pamplona",
                    "Peñablanca",
                    "Piat",
                    "Rizal",
                    "Sanchez-Mira",
                    "Santa Ana",
                    "Santa Praxedes",
                    "Santa Teresita",
                    "Santo Niño",
                    "Solana",
                    "Tuao",
                    "Tuguegarao City",
                ],
            },
            {
                name: "Isabela",
                municipalities: [
                    "Alicia",
                    "Angadanan",
                    "Aurora",
                    "Benito Soliven",
                    "Burgos",
                    "Cabagan",
                    "Cabatuan",
                    "Cauayan City",
                    "Cordon",
                    "Delfin Albano",
                    "Dinapigue",
                    "Divilacan",
                    "Echague",
                    "Gamu",
                    "Ilagan City",
                    "Jones",
                    "Luna",
                    "Maconacon",
                    "Mallig",
                    "Naguilian",
                    "Palanan",
                    "Quezon",
                    "Quirino",
                    "Ramon",
                    "Reina Mercedes",
                    "Roxas",
                    "San Agustin",
                    "San Guillermo",
                    "San Isidro",
                    "San Manuel",
                    "San Mariano",
                    "San Mateo",
                    "San Pablo",
                    "Santa Maria",
                    "Santiago City",
                    "Santo Tomas",
                    "Tumauini",
                ],
            },
            {
                name: "Nueva Vizcaya",
                municipalities: [
                    "Alfonso Castañeda",
                    "Ambaguio",
                    "Aritao",
                    "Bagabag",
                    "Bambang",
                    "Bayombong",
                    "Diadi",
                    "Dupax del Norte",
                    "Dupax del Sur",
                    "Kasibu",
                    "Kayapa",
                    "Quezon",
                    "Santa Fe",
                    "Solano",
                    "Villaverde",
                ],
            },
            {
                name: "Quirino",
                municipalities: [
                    "Aglipay",
                    "Cabarroguis",
                    "Diffun",
                    "Maddela",
                    "Nagtipunan",
                    "Saguday",
                ],
            },
        ],
    },
    {
        region: "Region III - Central Luzon",
        provinces: [
            {
                name: "Aurora",
                municipalities: [
                    "Baler",
                    "Casiguran",
                    "Dilasag",
                    "Dinalungan",
                    "Dingalan",
                    "Dipaculao",
                    "Maria Aurora",
                    "San Luis",
                ],
            },
            {
                name: "Bataan",
                municipalities: [
                    "Abucay",
                    "Bagac",
                    "Balanga City",
                    "Dinalupihan",
                    "Hermosa",
                    "Limay",
                    "Mariveles",
                    "Morong",
                    "Orani",
                    "Orion",
                    "Pilar",
                    "Samal",
                ],
            },
            {
                name: "Bulacan",
                municipalities: [
                    "Angat",
                    "Balagtas",
                    "Baliuag",
                    "Bocaue",
                    "Bulakan",
                    "Bustos",
                    "Calumpit",
                    "Doña Remedios Trinidad",
                    "Guiguinto",
                    "Hagonoy",
                    "Malolos City",
                    "Marilao",
                    "Meycauayan City",
                    "Norzagaray",
                    "Obando",
                    "Pandi",
                    "Paombong",
                    "Plaridel",
                    "Pulilan",
                    "San Ildefonso",
                    "San Jose del Monte City",
                    "San Miguel",
                    "San Rafael",
                    "Santa Maria",
                ],
            },
            {
                name: "Nueva Ecija",
                municipalities: [
                    "Aliaga",
                    "Bongabon",
                    "Cabanatuan City",
                    "Cabiao",
                    "Carranglan",
                    "Cuyapo",
                    "Gabaldon",
                    "Gapan City",
                    "General Mamerto Natividad",
                    "General Tinio",
                    "Guimba",
                    "Jaen",
                    "Laur",
                    "Licab",
                    "Llanera",
                    "Lupao",
                    "Muñoz City",
                    "Nampicuan",
                    "Palayan City",
                    "Pantabangan",
                    "Peñaranda",
                    "Quezon",
                    "Rizal",
                    "San Antonio",
                    "San Isidro",
                    "San Jose City",
                    "San Leonardo",
                    "Santa Rosa",
                    "Santo Domingo",
                    "Talavera",
                    "Talugtug",
                    "Zaragoza",
                ],
            },
            {
                name: "Pampanga",
                municipalities: [
                    "Angeles City",
                    "Apalit",
                    "Arayat",
                    "Bacolor",
                    "Candaba",
                    "Floridablanca",
                    "Guagua",
                    "Lubao",
                    "Mabalacat City",
                    "Macabebe",
                    "Magalang",
                    "Masantol",
                    "Mexico",
                    "Minalin",
                    "Porac",
                    "San Fernando City",
                    "San Luis",
                    "San Simon",
                    "Santa Ana",
                    "Santa Rita",
                    "Santo Tomas",
                    "Sasmuan",
                ],
            },
            {
                name: "Tarlac",
                municipalities: [
                    "Anao",
                    "Bamban",
                    "Camiling",
                    "Capas",
                    "Concepcion",
                    "Gerona",
                    "La Paz",
                    "Mayantoc",
                    "Moncada",
                    "Paniqui",
                    "Pura",
                    "Ramos",
                    "San Clemente",
                    "San Jose",
                    "San Manuel",
                    "Santa Ignacia",
                    "Tarlac City",
                    "Victoria",
                ],
            },
            {
                name: "Zambales",
                municipalities: [
                    "Botolan",
                    "Cabangan",
                    "Candelaria",
                    "Castillejos",
                    "Iba",
                    "Masinloc",
                    "Olongapo City",
                    "Palauig",
                    "San Antonio",
                    "San Felipe",
                    "San Marcelino",
                    "San Narciso",
                    "Santa Cruz",
                    "Subic",
                ],
            },
        ],
    },
    {
        region: "Region IV-A - CALABARZON",
        provinces: [
            {
                name: "Batangas",
                municipalities: [
                    "Agoncillo",
                    "Alitagtag",
                    "Balayan",
                    "Balete",
                    "Bauan",
                    "Calaca",
                    "Calatagan",
                    "Cuenca",
                    "Ibaan",
                    "Laurel",
                    "Lemery",
                    "Lian",
                    "Lipa City",
                    "Lobo",
                    "Mabini",
                    "Malvar",
                    "Mataas na Kahoy",
                    "Nasugbu",
                    "Padre Garcia",
                    "Rosario",
                    "San Jose",
                    "San Juan",
                    "San Luis",
                    "San Nicolas",
                    "San Pascual",
                    "Santa Teresita",
                    "Santo Tomas",
                    "Taal",
                    "Talisay",
                    "Tanauan City",
                    "Taysan",
                    "Tingloy",
                    "Tuy",
                ],
            },
            {
                name: "Cavite",
                municipalities: [
                    "Alfonso",
                    "Amadeo",
                    "Bacoor City",
                    "Carmona",
                    "Cavite City",
                    "Dasmariñas City",
                    "General Emilio Aguinaldo",
                    "General Mariano Alvarez",
                    "General Trias City",
                    "Imus City",
                    "Indang",
                    "Kawit",
                    "Magallanes",
                    "Maragondon",
                    "Mendez",
                    "Naic",
                    "Noveleta",
                    "Rosario",
                    "Silang",
                    "Tagaytay City",
                    "Tanza",
                    "Ternate",
                    "Trece Martires City",
                ],
            },
            {
                name: "Laguna",
                municipalities: [
                    "Alaminos",
                    "Bay",
                    "Biñan City",
                    "Cabuyao City",
                    "Calamba City",
                    "Calauan",
                    "Cavinti",
                    "Famy",
                    "Kalayaan",
                    "Liliw",
                    "Los Baños",
                    "Luisiana",
                    "Lumban",
                    "Mabitac",
                    "Magdalena",
                    "Majayjay",
                    "Nagcarlan",
                    "Paete",
                    "Pagsanjan",
                    "Pakil",
                    "Pangil",
                    "Pila",
                    "Rizal",
                    "San Pablo City",
                    "San Pedro City",
                    "Santa Cruz",
                    "Santa Maria",
                    "Santa Rosa City",
                    "Siniloan",
                    "Victoria",
                ],
            },
            {
                name: "Quezon",
                municipalities: [
                    "Agdangan",
                    "Alabat",
                    "Atimonan",
                    "Buenavista",
                    "Burdeos",
                    "Calauag",
                    "Candelaria",
                    "Catanauan",
                    "Dolores",
                    "General Luna",
                    "General Nakar",
                    "Guinayangan",
                    "Gumaca",
                    "Infanta",
                    "Jomalig",
                    "Lopez",
                    "Lucban",
                    "Lucena City",
                    "Macalelon",
                    "Mauban",
                    "Mulanay",
                    "Padre Burgos",
                    "Pagbilao",
                    "Panukulan",
                    "Patnanungan",
                    "Perez",
                    "Pitogo",
                    "Plaridel",
                    "Polillo",
                    "Quezon",
                    "Real",
                    "Sampaloc",
                    "San Andres",
                    "San Antonio",
                    "San Francisco",
                    "San Narciso",
                    "Sariaya",
                    "Tagkawayan",
                    "Tayabas City",
                    "Tiaong",
                    "Unisan",
                ],
            },
            {
                name: "Rizal",
                municipalities: [
                    "Angono",
                    "Baras",
                    "Binangonan",
                    "Cainta",
                    "Cardona",
                    "Jalajala",
                    "Morong",
                    "Pililla",
                    "Rodriguez",
                    "San Mateo",
                    "Tanay",
                    "Taytay",
                    "Teresa",
                ],
            },
        ],
    },
    {
        region: "Region IV-B - MIMAROPA",
        provinces: [
            {
                name: "Marinduque",
                municipalities: [
                    "Boac",
                    "Buenavista",
                    "Gasan",
                    "Mogpog",
                    "Santa Cruz",
                    "Torrijos",
                ],
            },
            {
                name: "Occidental Mindoro",
                municipalities: [
                    "Abra de Ilog",
                    "Calintaan",
                    "Looc",
                    "Lubang",
                    "Magsaysay",
                    "Mamburao",
                    "Paluan",
                    "Rizal",
                    "Sablayan",
                    "San Jose",
                    "Santa Cruz",
                ],
            },
            {
                name: "Oriental Mindoro",
                municipalities: [
                    "Baco",
                    "Bansud",
                    "Bongabong",
                    "Bulalacao",
                    "Calapan City",
                    "Gloria",
                    "Mansalay",
                    "Naujan",
                    "Pinamalayan",
                    "Pola",
                    "Puerto Galera",
                    "Roxas",
                    "San Teodoro",
                    "Socorro",
                    "Victoria",
                ],
            },
            {
                name: "Palawan",
                municipalities: [
                    "Aborlan",
                    "Agutaya",
                    "Araceli",
                    "Balabac",
                    "Bataraza",
                    "Brooke's Point",
                    "Busuanga",
                    "Cagayancillo",
                    "Coron",
                    "Culion",
                    "Cuyo",
                    "Dumaran",
                    "El Nido",
                    "Kalayaan",
                    "Linapacan",
                    "Magsaysay",
                    "Narra",
                    "Puerto Princesa City",
                    "Quezon",
                    "Rizal",
                    "Roxas",
                    "San Vicente",
                    "Sofronio Española",
                    "Taytay",
                ],
            },
            {
                name: "Romblon",
                municipalities: [
                    "Alcantara",
                    "Banton",
                    "Cajidiocan",
                    "Calatrava",
                    "Concepcion",
                    "Corcuera",
                    "Ferrol",
                    "Looc",
                    "Magdiwang",
                    "Odiongan",
                    "Romblon",
                    "San Agustin",
                    "San Andres",
                    "San Fernando",
                    "San Jose",
                    "Santa Fe",
                    "Santa Maria",
                ],
            },
        ],
    },
    {
        region: "Region V - Bicol Region",
        provinces: [
            {
                name: "Albay",
                municipalities: [
                    "Bacacay",
                    "Camalig",
                    "Daraga",
                    "Guinobatan",
                    "Jovellar",
                    "Legazpi City",
                    "Libon",
                    "Ligao City",
                    "Malilipot",
                    "Malinao",
                    "Manito",
                    "Oas",
                    "Pio Duran",
                    "Polangui",
                    "Rapu-Rapu",
                    "Santo Domingo",
                    "Tabaco City",
                    "Tiwi",
                ],
            },
            {
                name: "Camarines Norte",
                municipalities: [
                    "Basud",
                    "Capalonga",
                    "Daet",
                    "Jose Panganiban",
                    "Labo",
                    "Mercedes",
                    "Paracale",
                    "San Lorenzo Ruiz",
                    "San Vicente",
                    "Santa Elena",
                    "Talisay",
                    "Vinzons",
                ],
            },
            {
                name: "Camarines Sur",
                municipalities: [
                    "Baao",
                    "Balatan",
                    "Bato",
                    "Bombon",
                    "Buhi",
                    "Bula",
                    "Cabusao",
                    "Calabanga",
                    "Camaligan",
                    "Canaman",
                    "Caramoan",
                    "Del Gallego",
                    "Gainza",
                    "Garchitorena",
                    "Goa",
                    "Iriga City",
                    "Lagonoy",
                    "Libmanan",
                    "Lupi",
                    "Magarao",
                    "Milaor",
                    "Minalabac",
                    "Nabua",
                    "Naga City",
                    "Ocampo",
                    "Pamplona",
                    "Pasacao",
                    "Pili",
                    "Presentacion",
                    "Ragay",
                    "Sagñay",
                    "San Fernando",
                    "San Jose",
                    "Sipocot",
                    "Siruma",
                    "Tigaon",
                    "Tinambac",
                ],
            },
            {
                name: "Catanduanes",
                municipalities: [
                    "Bagamanoc",
                    "Baras",
                    "Bato",
                    "Caramoran",
                    "Gigmoto",
                    "Pandan",
                    "Panganiban",
                    "San Andres",
                    "San Miguel",
                    "Viga",
                    "Virac",
                ],
            },
            {
                name: "Masbate",
                municipalities: [
                    "Aroroy",
                    "Baleno",
                    "Balud",
                    "Batuan",
                    "Cataingan",
                    "Cawayan",
                    "Claveria",
                    "Dimasalang",
                    "Esperanza",
                    "Mandaon",
                    "Masbate City",
                    "Milagros",
                    "Mobo",
                    "Monreal",
                    "Palanas",
                    "Pio V. Corpuz",
                    "Placer",
                    "San Fernando",
                    "San Jacinto",
                    "San Pascual",
                    "Uson",
                ],
            },
            {
                name: "Sorsogon",
                municipalities: [
                    "Barcelona",
                    "Bulan",
                    "Bulusan",
                    "Casiguran",
                    "Castilla",
                    "Donsol",
                    "Gubat",
                    "Irosin",
                    "Juban",
                    "Magallanes",
                    "Matnog",
                    "Pilar",
                    "Prieto Diaz",
                    "Santa Magdalena",
                    "Sorsogon City",
                ],
            },
        ],
    },
    {
        region: "Region VI - Western Visayas",
        provinces: [
            {
                name: "Aklan",
                municipalities: [
                    "Altavas",
                    "Balete",
                    "Banga",
                    "Batan",
                    "Buruanga",
                    "Ibajay",
                    "Kalibo",
                    "Lezo",
                    "Libacao",
                    "Madalag",
                    "Makato",
                    "Malay",
                    "Malinao",
                    "Nabas",
                    "New Washington",
                    "Numancia",
                    "Tangalan",
                ],
            },
            {
                name: "Antique",
                municipalities: [
                    "Anini-y",
                    "Barbaza",
                    "Belison",
                    "Bugasong",
                    "Caluya",
                    "Culasi",
                    "Hamtic",
                    "Laua-an",
                    "Libertad",
                    "Pandan",
                    "Patnongon",
                    "San Jose",
                    "San Remigio",
                    "Sebaste",
                    "Sibalom",
                    "Tibiao",
                    "Tobias Fornier",
                    "Valderrama",
                ],
            },
            {
                name: "Capiz",
                municipalities: [
                    "Cuartero",
                    "Dao",
                    "Dumalag",
                    "Dumarao",
                    "Ivisan",
                    "Jamindan",
                    "Maayon",
                    "Mambusao",
                    "Panay",
                    "Panitan",
                    "Pilar",
                    "Pontevedra",
                    "President Roxas",
                    "Roxas City",
                    "Sapian",
                    "Sigma",
                    "Tapaz",
                ],
            },
            {
                name: "Guimaras",
                municipalities: [
                    "Buenavista",
                    "Jordan",
                    "Nueva Valencia",
                    "San Lorenzo",
                    "Sibunag",
                ],
            },
            {
                name: "Iloilo",
                municipalities: [
                    "Ajuy",
                    "Alimodian",
                    "Anilao",
                    "Badiangan",
                    "Balasan",
                    "Banate",
                    "Barotac Nuevo",
                    "Barotac Viejo",
                    "Batad",
                    "Bingawan",
                    "Cabatuan",
                    "Calinog",
                    "Carles",
                    "Concepcion",
                    "Dingle",
                    "Dueñas",
                    "Dumangas",
                    "Estancia",
                    "Guimbal",
                    "Igbaras",
                    "Janiuay",
                    "Lambunao",
                    "Leganes",
                    "Lemery",
                    "Leon",
                    "Maasin",
                    "Miagao",
                    "Mina",
                    "New Lucena",
                    "Oton",
                    "Passi City",
                    "Pavia",
                    "Pototan",
                    "San Dionisio",
                    "San Enrique",
                    "San Joaquin",
                    "San Miguel",
                    "San Rafael",
                    "Santa Barbara",
                    "Sara",
                    "Tigbauan",
                    "Tubungan",
                    "Zarraga",
                ],
            },
            {
                name: "Negros Occidental",
                municipalities: [
                    "Bacolod City",
                    "Bago City",
                    "Binalbagan",
                    "Cadiz City",
                    "Calatrava",
                    "Candoni",
                    "Cauayan",
                    "Enrique B. Magalona",
                    "Escalante City",
                    "Himamaylan City",
                    "Hinigaran",
                    "Hinoba-an",
                    "Ilog",
                    "Isabela",
                    "Kabankalan City",
                    "La Carlota City",
                    "La Castellana",
                    "Manapla",
                    "Moises Padilla",
                    "Murcia",
                    "Pontevedra",
                    "Pulupandan",
                    "Sagay City",
                    "Salvador Benedicto",
                    "San Carlos City",
                    "San Enrique",
                    "Silay City",
                    "Sipalay City",
                    "Talisay City",
                    "Toboso",
                    "Valladolid",
                    "Victorias City",
                ],
            },
        ],
    },
    {
        region: "Region VII - Central Visayas",
        provinces: [
            {
                name: "Bohol",
                municipalities: [
                    "Alburquerque",
                    "Alicia",
                    "Anda",
                    "Antequera",
                    "Baclayon",
                    "Balilihan",
                    "Batuan",
                    "Bien Unido",
                    "Bilar",
                    "Buenavista",
                    "Calape",
                    "Candijay",
                    "Carmen",
                    "Catigbian",
                    "Clarin",
                    "Corella",
                    "Cortes",
                    "Dagohoy",
                    "Danao",
                    "Dauis",
                    "Dimiao",
                    "Duero",
                    "Garcia Hernandez",
                    "Guindulman",
                    "Inabanga",
                    "Jagna",
                    "Lila",
                    "Loay",
                    "Loboc",
                    "Loon",
                    "Mabini",
                    "Maribojoc",
                    "Panglao",
                    "Pilar",
                    "President Carlos P. Garcia",
                    "Sagbayan",
                    "San Isidro",
                    "San Miguel",
                    "Sevilla",
                    "Sierra Bullones",
                    "Sikatuna",
                    "Tagbilaran City",
                    "Talibon",
                    "Trinidad",
                    "Tubigon",
                    "Ubay",
                    "Valencia",
                ],
            },
            {
                name: "Cebu",
                municipalities: [
                    "Alcantara",
                    "Alcoy",
                    "Alegria",
                    "Aloguinsan",
                    "Argao",
                    "Asturias",
                    "Badian",
                    "Balamban",
                    "Bantayan",
                    "Barili",
                    "Bogo City",
                    "Boljoon",
                    "Borbon",
                    "Carcar City",
                    "Carmen",
                    "Catmon",
                    "Cebu City",
                    "Compostela",
                    "Consolacion",
                    "Cordoba",
                    "Daanbantayan",
                    "Dalaguete",
                    "Danao City",
                    "Dumanjug",
                    "Ginatilan",
                    "Lapu-Lapu City",
                    "Liloan",
                    "Madridejos",
                    "Malabuyoc",
                    "Mandaue City",
                    "Medellin",
                    "Minglanilla",
                    "Moalboal",
                    "Naga City",
                    "Oslob",
                    "Pilar",
                    "Pinamungahan",
                    "Poro",
                    "Ronda",
                    "Samboan",
                    "San Fernando",
                    "San Francisco",
                    "San Remigio",
                    "Santa Fe",
                    "Santander",
                    "Sibonga",
                    "Sogod",
                    "Tabogon",
                    "Tabuelan",
                    "Talisay City",
                    "Toledo City",
                    "Tuburan",
                    "Tudela",
                ],
            },
            {
                name: "Negros Oriental",
                municipalities: [
                    "Amlan",
                    "Ayungon",
                    "Bacong",
                    "Bais City",
                    "Basay",
                    "Bayawan City",
                    "Bindoy",
                    "Canlaon City",
                    "Dauin",
                    "Dumaguete City",
                    "Guihulngan City",
                    "Jimalalud",
                    "La Libertad",
                    "Mabinay",
                    "Manjuyod",
                    "Pamplona",
                    "San Jose",
                    "Santa Catalina",
                    "Siaton",
                    "Sibulan",
                    "Tanjay City",
                    "Tayasan",
                    "Valencia",
                    "Vallehermoso",
                    "Zamboanguita",
                ],
            },
            {
                name: "Siquijor",
                municipalities: [
                    "Enrique Villanueva",
                    "Larena",
                    "Lazi",
                    "Maria",
                    "San Juan",
                    "Siquijor",
                ],
            },
        ],
    },
    {
        region: "Region VIII - Eastern Visayas",
        provinces: [
            {
                name: "Biliran",
                municipalities: [
                    "Almeria",
                    "Biliran",
                    "Cabucgayan",
                    "Caibiran",
                    "Culaba",
                    "Kawayan",
                    "Maripipi",
                    "Naval",
                ],
            },
            {
                name: "Eastern Samar",
                municipalities: [
                    "Arteche",
                    "Balangiga",
                    "Balangkayan",
                    "Borongan City",
                    "Can-avid",
                    "Dolores",
                    "General MacArthur",
                    "Giporlos",
                    "Guiuan",
                    "Hernani",
                    "Jipapad",
                    "Lawaan",
                    "Llorente",
                    "Maslog",
                    "Maydolong",
                    "Mercedes",
                    "Oras",
                    "Quinapondan",
                    "Salcedo",
                    "San Julian",
                    "San Policarpo",
                    "Sulat",
                    "Taft",
                ],
            },
            {
                name: "Leyte",
                municipalities: [
                    "Abuyog",
                    "Alangalang",
                    "Albuera",
                    "Babatngon",
                    "Barugo",
                    "Bato",
                    "Baybay City",
                    "Burauen",
                    "Calubian",
                    "Capoocan",
                    "Carigara",
                    "Dagami",
                    "Dulag",
                    "Hilongos",
                    "Hindang",
                    "Inopacan",
                    "Isabel",
                    "Jaro",
                    "Javier",
                    "Julita",
                    "Kananga",
                    "La Paz",
                    "Leyte",
                    "MacArthur",
                    "Mahaplag",
                    "Matag-ob",
                    "Matalom",
                    "Mayorga",
                    "Merida",
                    "Ormoc City",
                    "Palo",
                    "Palompon",
                    "Pastrana",
                    "San Isidro",
                    "San Miguel",
                    "Santa Fe",
                    "Tabango",
                    "Tabontabon",
                    "Tacloban City",
                    "Tanauan",
                    "Tolosa",
                    "Tunga",
                    "Villaba",
                ],
            },
            {
                name: "Northern Samar",
                municipalities: [
                    "Allen",
                    "Biri",
                    "Bobon",
                    "Capul",
                    "Catarman",
                    "Catubig",
                    "Gamay",
                    "Laoang",
                    "Lapinig",
                    "Las Navas",
                    "Lavezares",
                    "Lope de Vega",
                    "Mapanas",
                    "Mondragon",
                    "Palapag",
                    "Pambujan",
                    "Rosario",
                    "San Antonio",
                    "San Isidro",
                    "San Jose",
                    "San Roque",
                    "San Vicente",
                    "Silvino Lobos",
                    "Victoria",
                ],
            },
            {
                name: "Samar",
                municipalities: [
                    "Almagro",
                    "Basey",
                    "Calbayog City",
                    "Calbiga",
                    "Catbalogan City",
                    "Daram",
                    "Gandara",
                    "Hinabangan",
                    "Jiabong",
                    "Marabut",
                    "Matuguinao",
                    "Motiong",
                    "Pagsanghan",
                    "Paranas",
                    "Pinabacdao",
                    "San Jorge",
                    "San Jose de Buan",
                    "San Sebastian",
                    "Santa Margarita",
                    "Santa Rita",
                    "Santo Niño",
                    "Tagapul-an",
                    "Talalora",
                    "Tarangnan",
                    "Villareal",
                    "Zumarraga",
                ],
            },
            {
                name: "Southern Leyte",
                municipalities: [
                    "Anahawan",
                    "Bontoc",
                    "Hinunangan",
                    "Hinundayan",
                    "Libagon",
                    "Liloan",
                    "Limasawa",
                    "Maasin City",
                    "Macrohon",
                    "Malitbog",
                    "Padre Burgos",
                    "Pintuyan",
                    "Saint Bernard",
                    "San Francisco",
                    "San Juan",
                    "San Ricardo",
                    "Silago",
                    "Sogod",
                    "Tomas Oppus",
                ],
            },
        ],
    },
    {
        region: "Region IX - Zamboanga Peninsula",
        provinces: [
            {
                name: "Zamboanga del Norte",
                municipalities: [
                    "Baliguian",
                    "Dapitan City",
                    "Dipolog City",
                    "Godod",
                    "Gutalac",
                    "Jose Dalman",
                    "Kalawit",
                    "Katipunan",
                    "La Libertad",
                    "Labason",
                    "Liloy",
                    "Manukan",
                    "Mutia",
                    "Piñan",
                    "Polanco",
                    "Rizal",
                    "Roxas",
                    "Salug",
                    "Sergio Osmeña Sr.",
                    "Siayan",
                    "Sibuco",
                    "Sibutad",
                    "Sindangan",
                    "Siocon",
                    "Sirawai",
                    "Tampilisan",
                ],
            },
            {
                name: "Zamboanga del Sur",
                municipalities: [
                    "Aurora",
                    "Bayog",
                    "Dimataling",
                    "Dinas",
                    "Dumalinao",
                    "Dumingag",
                    "Guipos",
                    "Josefina",
                    "Kumalarang",
                    "Labangan",
                    "Lakewood",
                    "Lapuyan",
                    "Mahayag",
                    "Margosatubig",
                    "Midsalip",
                    "Molave",
                    "Pagadian City",
                    "Pitogo",
                    "Ramon Magsaysay",
                    "San Miguel",
                    "San Pablo",
                    "Sominot",
                    "Tabina",
                    "Tambulig",
                    "Tigbao",
                    "Tukuran",
                    "Vincenzo A. Sagun",
                    "Zamboanga City",
                ],
            },
            {
                name: "Zamboanga Sibugay",
                municipalities: [
                    "Alicia",
                    "Buug",
                    "Diplahan",
                    "Imelda",
                    "Ipil",
                    "Kabasalan",
                    "Mabuhay",
                    "Malangas",
                    "Naga",
                    "Olutanga",
                    "Payao",
                    "Roseller Lim",
                    "Siay",
                    "Talusan",
                    "Titay",
                    "Tungawan",
                ],
            },
        ],
    },
    {
        region: "Region X - Northern Mindanao",
        provinces: [
            {
                name: "Bukidnon",
                municipalities: [
                    "Baungon",
                    "Cabanglasan",
                    "Damulog",
                    "Dangcagan",
                    "Don Carlos",
                    "Impasug-ong",
                    "Kadingilan",
                    "Kalilangan",
                    "Kibawe",
                    "Kitaotao",
                    "Lantapan",
                    "Libona",
                    "Malaybalay City",
                    "Malitbog",
                    "Manolo Fortich",
                    "Maramag",
                    "Pangantucan",
                    "Quezon",
                    "San Fernando",
                    "Sumilao",
                    "Talakag",
                    "Valencia City",
                ],
            },
            {
                name: "Camiguin",
                municipalities: [
                    "Catarman",
                    "Guinsiliban",
                    "Mahinog",
                    "Mambajao",
                    "Sagay",
                ],
            },
            {
                name: "Lanao del Norte",
                municipalities: [
                    "Bacolod",
                    "Baloi",
                    "Baroy",
                    "Kapatagan",
                    "Karomatan",
                    "Kauswagan",
                    "Kolambugan",
                    "Lala",
                    "Linamon",
                    "Magsaysay",
                    "Maigo",
                    "Matungao",
                    "Munai",
                    "Nunungan",
                    "Pantao Ragat",
                    "Pantar",
                    "Poona Piagapo",
                    "Salvador",
                    "Sapad",
                    "Sultan Naga Dimaporo",
                    "Tagoloan",
                    "Tangcal",
                    "Tubod",
                ],
            },
            {
                name: "Misamis Occidental",
                municipalities: [
                    "Aloran",
                    "Baliangao",
                    "Bonifacio",
                    "Calamba",
                    "Clarin",
                    "Concepcion",
                    "Don Victoriano Chiongbian",
                    "Jimenez",
                    "Lopez Jaena",
                    "Oroquieta City",
                    "Ozamiz City",
                    "Panaon",
                    "Plaridel",
                    "Sapang Dalaga",
                    "Sinacaban",
                    "Tangub City",
                    "Tudela",
                ],
            },
            {
                name: "Misamis Oriental",
                municipalities: [
                    "Alubijid",
                    "Balingasag",
                    "Balingoan",
                    "Binuangan",
                    "Claveria",
                    "El Salvador City",
                    "Gingoog City",
                    "Gitagum",
                    "Initao",
                    "Jasaan",
                    "Kinoguitan",
                    "Lagonglong",
                    "Laguindingan",
                    "Libertad",
                    "Lugait",
                    "Magsaysay",
                    "Manticao",
                    "Medina",
                    "Naawan",
                    "Opol",
                    "Salay",
                    "Sugbongcogon",
                    "Tagoloan",
                    "Talisayan",
                    "Villanueva",
                ],
            },
        ],
    },
    {
        region: "Region XI - Davao Region",
        provinces: [
            {
                name: "Davao de Oro",
                municipalities: [
                    "Compostela",
                    "Laak",
                    "Mabini",
                    "Maco",
                    "Maragusan",
                    "Mawab",
                    "Monkayo",
                    "Montevista",
                    "Nabunturan",
                    "New Bataan",
                    "Pantukan",
                ],
            },
            {
                name: "Davao del Norte",
                municipalities: [
                    "Asuncion",
                    "Braulio E. Dujali",
                    "Carmen",
                    "Kapalong",
                    "New Corella",
                    "Panabo City",
                    "Samal City",
                    "San Isidro",
                    "Santo Tomas",
                    "Tagum City",
                    "Talaingod",
                ],
            },
            {
                name: "Davao del Sur",
                municipalities: [
                    "Bansalan",
                    "Davao City",
                    "Digos City",
                    "Hagonoy",
                    "Kiblawan",
                    "Magsaysay",
                    "Malalag",
                    "Matanao",
                    "Padada",
                    "Santa Cruz",
                    "Sulop",
                ],
            },
            {
                name: "Davao Occidental",
                municipalities: [
                    "Don Marcelino",
                    "Jose Abad Santos",
                    "Malita",
                    "Santa Maria",
                    "Sarangani",
                ],
            },
            {
                name: "Davao Oriental",
                municipalities: [
                    "Baganga",
                    "Banaybanay",
                    "Boston",
                    "Caraga",
                    "Cateel",
                    "Governor Generoso",
                    "Lupon",
                    "Manay",
                    "Mati City",
                    "San Isidro",
                    "Tarragona",
                ],
            },
        ],
    },
    {
        region: "Region XII - SOCCSKSARGEN",
        provinces: [
            {
                name: "Cotabato",
                municipalities: [
                    "Alamada",
                    "Aleosan",
                    "Antipas",
                    "Arakan",
                    "Banisilan",
                    "Carmen",
                    "Kabacan",
                    "Kidapawan City",
                    "Libungan",
                    "Magpet",
                    "Makilala",
                    "Matalam",
                    "Midsayap",
                    "Pigcawayan",
                    "Pikit",
                    "President Roxas",
                    "Tulunan",
                ],
            },
            {
                name: "Sarangani",
                municipalities: [
                    "Alabel",
                    "Glan",
                    "Kiamba",
                    "Maasim",
                    "Maitum",
                    "Malapatan",
                    "Malungon",
                ],
            },
            {
                name: "South Cotabato",
                municipalities: [
                    "Banga",
                    "General Santos City",
                    "Koronadal City",
                    "Lake Sebu",
                    "Norala",
                    "Polomolok",
                    "Santo Niño",
                    "Surallah",
                    "Tampakan",
                    "Tantangan",
                    "T'boli",
                    "Tupi",
                ],
            },
            {
                name: "Sultan Kudarat",
                municipalities: [
                    "Bagumbayan",
                    "Columbio",
                    "Esperanza",
                    "Isulan",
                    "Kalamansig",
                    "Lambayong",
                    "Lebak",
                    "Lutayan",
                    "Palimbang",
                    "President Quirino",
                    "Senator Ninoy Aquino",
                    "Tacurong City",
                ],
            },
        ],
    },
    {
        region: "Region XIII - Caraga",
        provinces: [
            {
                name: "Agusan del Norte",
                municipalities: [
                    "Buenavista",
                    "Butuan City",
                    "Cabadbaran City",
                    "Carmen",
                    "Jabonga",
                    "Kitcharao",
                    "Las Nieves",
                    "Magallanes",
                    "Nasipit",
                    "Remedios T. Romualdez",
                    "Santiago",
                    "Tubay",
                ],
            },
            {
                name: "Agusan del Sur",
                municipalities: [
                    "Bayugan City",
                    "Bunawan",
                    "Esperanza",
                    "La Paz",
                    "Loreto",
                    "Prosperidad",
                    "Rosario",
                    "San Francisco",
                    "San Luis",
                    "Santa Josefa",
                    "Sibagat",
                    "Talacogon",
                    "Trento",
                    "Veruela",
                ],
            },
            {
                name: "Dinagat Islands",
                municipalities: [
                    "Basilisa",
                    "Cagdianao",
                    "Dinagat",
                    "Libjo",
                    "Loreto",
                    "San Jose",
                    "Tubajon",
                ],
            },
            {
                name: "Surigao del Norte",
                municipalities: [
                    "Alegria",
                    "Bacuag",
                    "Burgos",
                    "Claver",
                    "Dapa",
                    "Del Carmen",
                    "General Luna",
                    "Gigaquit",
                    "Mainit",
                    "Malimono",
                    "Placer",
                    "San Benito",
                    "San Francisco",
                    "San Isidro",
                    "Santa Monica",
                    "Sison",
                    "Socorro",
                    "Surigao City",
                    "Tagana-an",
                    "Tubod",
                ],
            },
            {
                name: "Surigao del Sur",
                municipalities: [
                    "Barobo",
                    "Bayabas",
                    "Bislig City",
                    "Cagwait",
                    "Cantilan",
                    "Carmen",
                    "Carrascal",
                    "Cortes",
                    "Hinatuan",
                    "Lanuza",
                    "Lianga",
                    "Lingig",
                    "Madrid",
                    "Marihatag",
                    "San Agustin",
                    "San Miguel",
                    "Tagbina",
                    "Tago",
                    "Tandag City",
                ],
            },
        ],
    },
    {
        region: "BARMM - Bangsamoro Autonomous Region in Muslim Mindanao",
        provinces: [
            {
                name: "Basilan",
                municipalities: [
                    "Akbar",
                    "Al-Barka",
                    "Hadji Mohammad Ajul",
                    "Hadji Muhtamad",
                    "Isabela City",
                    "Lamitan City",
                    "Lantawan",
                    "Maluso",
                    "Sumisip",
                    "Tabuan-Lasa",
                    "Tipo-Tipo",
                    "Tuburan",
                    "Ungkaya Pukan",
                ],
            },
            {
                name: "Lanao del Sur",
                municipalities: [
                    "Bacolod-Kalawi",
                    "Balabagan",
                    "Balindong",
                    "Bayang",
                    "Binidayan",
                    "Buadiposo-Buntong",
                    "Bubong",
                    "Butig",
                    "Calanogas",
                    "Ditsaan-Ramain",
                    "Ganassi",
                    "Kapai",
                    "Kapatagan",
                    "Lumba-Bayabao",
                    "Lumbaca-Unayan",
                    "Lumbatan",
                    "Lumbayanague",
                    "Madalum",
                    "Madamba",
                    "Maguing",
                    "Malabang",
                    "Marantao",
                    "Marawi City",
                    "Marogong",
                    "Masiu",
                    "Mulondo",
                    "Pagayawan",
                    "Piagapo",
                    "Picong",
                    "Poona Bayabao",
                    "Pualas",
                    "Saguiaran",
                    "Sultan Dumalondong",
                    "Tagoloan II",
                    "Tamparan",
                    "Taraka",
                    "Tubaran",
                    "Tugaya",
                    "Wao",
                ],
            },
            {
                name: "Maguindanao",
                municipalities: [
                    "Ampatuan",
                    "Barira",
                    "Buldon",
                    "Buluan",
                    "Datu Abdullah Sangki",
                    "Datu Anggal Midtimbang",
                    "Datu Blah T. Sinsuat",
                    "Datu Hoffer Ampatuan",
                    "Datu Odin Sinsuat",
                    "Datu Paglas",
                    "Datu Piang",
                    "Datu Salibo",
                    "Datu Saudi-Ampatuan",
                    "Datu Unsay",
                    "Gen. S.K. Pendatun",
                    "Guindulungan",
                    "Kabuntalan",
                    "Mamasapano",
                    "Mangudadatu",
                    "Matanog",
                    "Northern Kabuntalan",
                    "Pagalungan",
                    "Paglat",
                    "Pandag",
                    "Parang",
                    "Rajah Buayan",
                    "Shariff Aguak",
                    "Shariff Saydona Mustapha",
                    "South Upi",
                    "Sultan Kudarat",
                    "Sultan Mastura",
                    "Sultan sa Barongis",
                    "Talayan",
                    "Talitay",
                    "Upi",
                ],
            },
            {
                name: "Sulu",
                municipalities: [
                    "Hadji Panglima Tahil",
                    "Indanan",
                    "Jolo",
                    "Kalingalan Caluang",
                    "Lugus",
                    "Luuk",
                    "Maimbung",
                    "Old Panamao",
                    "Omar",
                    "Pandami",
                    "Panglima Estino",
                    "Pangutaran",
                    "Parang",
                    "Pata",
                    "Patikul",
                    "Siasi",
                    "Talipao",
                    "Tapul",
                    "Tongkil",
                ],
            },
            {
                name: "Tawi-Tawi",
                municipalities: [
                    "Bongao",
                    "Languyan",
                    "Mapun",
                    "Panglima Sugala",
                    "Sapa-Sapa",
                    "Sibutu",
                    "Simunul",
                    "Sitangkai",
                    "South Ubian",
                    "Tandubas",
                    "Turtle Islands",
                ],
            },
        ],
    },
    {
        region: "CAR - Cordillera Administrative Region",
        provinces: [
            {
                name: "Abra",
                municipalities: [
                    "Bangued",
                    "Boliney",
                    "Bucay",
                    "Bucloc",
                    "Daguioman",
                    "Danglas",
                    "Dolores",
                    "La Paz",
                    "Lacub",
                    "Lagangilang",
                    "Lagayan",
                    "Langiden",
                    "Licuan-Baay",
                    "Luba",
                    "Malibcong",
                    "Manabo",
                    "Peñarrubia",
                    "Pidigan",
                    "Pilar",
                    "Sallapadan",
                    "San Isidro",
                    "San Juan",
                    "San Quintin",
                    "Tayum",
                    "Tineg",
                    "Tubo",
                    "Villaviciosa",
                ],
            },
            {
                name: "Apayao",
                municipalities: [
                    "Calanasan",
                    "Conner",
                    "Flora",
                    "Kabugao",
                    "Luna",
                    "Pudtol",
                    "Santa Marcela",
                ],
            },
            {
                name: "Benguet",
                municipalities: [
                    "Atok",
                    "Baguio City",
                    "Bakun",
                    "Bokod",
                    "Buguias",
                    "Itogon",
                    "Kabayan",
                    "Kapangan",
                    "Kibungan",
                    "La Trinidad",
                    "Mankayan",
                    "Sablan",
                    "Tuba",
                    "Tublay",
                ],
            },
            {
                name: "Ifugao",
                municipalities: [
                    "Aguinaldo",
                    "Alfonso Lista",
                    "Asipulo",
                    "Banaue",
                    "Hingyon",
                    "Hungduan",
                    "Kiangan",
                    "Lagawe",
                    "Lamut",
                    "Mayoyao",
                    "Tinoc",
                ],
            },
            {
                name: "Kalinga",
                municipalities: [
                    "Balbalan",
                    "Lubuagan",
                    "Pasil",
                    "Pinukpuk",
                    "Rizal",
                    "Tabuk City",
                    "Tanudan",
                    "Tinglayan",
                ],
            },
            {
                name: "Mountain Province",
                municipalities: [
                    "Barlig",
                    "Bauko",
                    "Besao",
                    "Bontoc",
                    "Natonin",
                    "Paracelis",
                    "Sabangan",
                    "Sadanga",
                    "Sagada",
                    "Tadian",
                ],
            },
        ],
    },
    {
        region: "NCR - National Capital Region",
        provinces: [
            {
                name: "Metro Manila",
                municipalities: [
                    "Caloocan City",
                    "Las Piñas City",
                    "Makati City",
                    "Malabon City",
                    "Mandaluyong City",
                    "Manila City",
                    "Marikina City",
                    "Muntinlupa City",
                    "Navotas City",
                    "Parañaque City",
                    "Pasay City",
                    "Pasig City",
                    "Pateros",
                    "Quezon City",
                    "San Juan City",
                    "Taguig City",
                    "Valenzuela City",
                ],
            },
        ],
    },
    {
        region: "NIR - Negros Island Region",
        provinces: [
            {
                name: "Negros Occidental",
                municipalities: [
                    "Bacolod City",
                    "Bago City",
                    "Binalbagan",
                    "Cadiz City",
                    "Calatrava",
                    "Candoni",
                    "Cauayan",
                    "Enrique B. Magalona",
                    "Escalante City",
                    "Himamaylan City",
                    "Hinigaran",
                    "Hinoba-an",
                    "Ilog",
                    "Isabela",
                    "Kabankalan City",
                    "La Carlota City",
                    "La Castellana",
                    "Manapla",
                    "Moises Padilla",
                    "Murcia",
                    "Pontevedra",
                    "Pulupandan",
                    "Sagay City",
                    "Salvador Benedicto",
                    "San Carlos City",
                    "San Enrique",
                    "Silay City",
                    "Sipalay City",
                    "Talisay City",
                    "Toboso",
                    "Valladolid",
                    "Victorias City",
                ],
            },
            {
                name: "Negros Oriental",
                municipalities: [
                    "Amlan",
                    "Ayungon",
                    "Bacong",
                    "Bais City",
                    "Basay",
                    "Bayawan City",
                    "Bindoy",
                    "Canlaon City",
                    "Dauin",
                    "Dumaguete City",
                    "Guihulngan City",
                    "Jimalalud",
                    "La Libertad",
                    "Mabinay",
                    "Manjuyod",
                    "Pamplona",
                    "San Jose",
                    "Santa Catalina",
                    "Siaton",
                    "Sibulan",
                    "Tanjay City",
                    "Tayasan",
                    "Valencia",
                    "Vallehermoso",
                    "Zamboanguita",
                ],
            },
            {
                name: "Siquijor",
                municipalities: [
                    "PROVINCIAL POSITIONS",
                    "ENRIQUE VILLANUEVA",
                    "LARENA",
                    "LAZI",
                    "MARIA",
                    "SAN JUAN",
                    "SIQUIJOR",
                ],
            },
        ],
    },
];